# Generated by Django 4.1 on 2022-08-05 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')])),
                ('code', models.IntegerField()),
                ('is_authenticated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'auth_code',
            },
        ),
    ]
